# -*- coding: utf-8 -*-
"""ab_testing_tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZuV_AtuTqCccWm9AVFREmR80Inertrf
"""

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind, chi2_contingency
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported!")

# Simulate A/B test data — Zomato button color test!
np.random.seed(42)

# Group A — Control (old blue button)
# Group B — Treatment (new green button)

n_users = 1000  # 1000 users per group

# Revenue per user (continuous data — for t-test)
group_a_revenue = np.random.normal(loc=250, scale=80, size=n_users)
group_b_revenue = np.random.normal(loc=270, scale=80, size=n_users)

# Conversions (0 or 1 — for chi-square test)
group_a_conversions = np.random.binomial(1, 0.12, size=n_users)
group_b_conversions = np.random.binomial(1, 0.15, size=n_users)

print("A/B Test Data Created!")
print(f"\nGroup A — Control:")
print(f"  Average Revenue: ₹{group_a_revenue.mean():.2f}")
print(f"  Conversion Rate: {group_a_conversions.mean()*100:.2f}%")
print(f"\nGroup B — Treatment:")
print(f"  Average Revenue: ₹{group_b_revenue.mean():.2f}")
print(f"  Conversion Rate: {group_b_conversions.mean()*100:.2f}%")

# T-test — is revenue difference statistically significant?
t_stat, p_value = ttest_ind(group_a_revenue, group_b_revenue)

print("=" * 50)
print("T-TEST RESULTS — Revenue Analysis")
print("=" * 50)
print(f"Group A Mean: ₹{group_a_revenue.mean():.2f}")
print(f"Group B Mean: ₹{group_b_revenue.mean():.2f}")
print(f"Difference:   ₹{group_b_revenue.mean() - group_a_revenue.mean():.2f}")
print(f"\nT-statistic: {t_stat:.4f}")
print(f"P-value:     {p_value:.4f}")
print()
if p_value < 0.05:
    print("✅ SIGNIFICANT! Green button generates more revenue!")
    print("   Recommendation: SHIP the green button!")
else:
    print("❌ NOT SIGNIFICANT! Difference is just luck!")
    print("   Recommendation: Keep the blue button!")
print("=" * 50)

# Chi-square test — is conversion rate difference significant?
conversions_a = group_a_conversions.sum()
no_conversions_a = n_users - conversions_a
conversions_b = group_b_conversions.sum()
no_conversions_b = n_users - conversions_b

# Contingency table
contingency_table = np.array([
    [conversions_a, no_conversions_a],
    [conversions_b, no_conversions_b]
])

chi2, p_value_chi2, dof, expected = chi2_contingency(contingency_table)

print("=" * 50)
print("CHI-SQUARE TEST — Conversion Rate Analysis")
print("=" * 50)
print(f"Group A Conversions: {conversions_a} / {n_users} = {conversions_a/n_users*100:.2f}%")
print(f"Group B Conversions: {conversions_b} / {n_users} = {conversions_b/n_users*100:.2f}%")
print(f"Lift: {((conversions_b/n_users) - (conversions_a/n_users))/(conversions_a/n_users)*100:.2f}%")
print(f"\nChi-square: {chi2:.4f}")
print(f"P-value:    {p_value_chi2:.4f}")
print()
if p_value_chi2 < 0.05:
    print("✅ SIGNIFICANT! Green button converts better!")
    print("   Recommendation: SHIP the green button!")
else:
    print("❌ NOT SIGNIFICANT! Difference is just luck!")
    print("   Recommendation: Keep the blue button!")
print("=" * 50)

import os

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Chart 1 — Revenue distribution
axes[0].hist(group_a_revenue, bins=30, alpha=0.6,
             color='blue', label='Group A (Control)')
axes[0].hist(group_b_revenue, bins=30, alpha=0.6,
             color='green', label='Group B (Treatment)')
axes[0].axvline(group_a_revenue.mean(), color='blue',
                linestyle='--', linewidth=2)
axes[0].axvline(group_b_revenue.mean(), color='green',
                linestyle='--', linewidth=2)
axes[0].set_title('Revenue Distribution — A vs B', fontsize=13)
axes[0].set_xlabel('Revenue (₹)')
axes[0].set_ylabel('Count')
axes[0].legend()

# Chart 2 — Conversion rates
conversion_data = pd.DataFrame({
    'Group': ['Control (A)', 'Treatment (B)'],
    'Conversion Rate (%)': [
        group_a_conversions.mean()*100,
        group_b_conversions.mean()*100
    ]
})
sns.barplot(data=conversion_data, x='Group',
            y='Conversion Rate (%)',
            hue='Group', legend=False,
            palette=['blue', 'green'], ax=axes[1])
axes[1].set_title('Conversion Rate — A vs B', fontsize=13)
axes[1].set_ylim(0, 20)

plt.suptitle('Zomato Button Color A/B Test Results',
             fontsize=15, fontweight='bold')
plt.tight_layout()
os.makedirs('screenshots', exist_ok=True)
plt.savefig('screenshots/ab_test_results.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("✅ Chart saved!")

def run_ab_test(group_a, group_b,
                metric_name='Revenue',
                alpha=0.05):
    """
    Complete A/B Test Analysis Tool

    Parameters:
    group_a: array — control group data
    group_b: array — treatment group data
    metric_name: str — what are we measuring
    alpha: float — significance level (default 0.05)
    """

    print("=" * 55)
    print(f"A/B TEST REPORT — {metric_name}")
    print("=" * 55)

    # Basic stats
    print(f"\n📊 DESCRIPTIVE STATISTICS:")
    print(f"  Control   (A): mean={group_a.mean():.2f}, "
          f"std={group_a.std():.2f}, n={len(group_a)}")
    print(f"  Treatment (B): mean={group_b.mean():.2f}, "
          f"std={group_b.std():.2f}, n={len(group_b)}")

    # Lift calculation
    lift = ((group_b.mean() - group_a.mean()) /
             group_a.mean()) * 100
    print(f"\n📈 LIFT: {lift:.2f}%")

    # T-test
    t_stat, p_value = ttest_ind(group_a, group_b)

    print(f"\n🔬 STATISTICAL TEST:")
    print(f"  T-statistic: {t_stat:.4f}")
    print(f"  P-value:     {p_value:.4f}")
    print(f"  Alpha:       {alpha}")

    # Confidence interval
    diff = group_b.mean() - group_a.mean()
    se = np.sqrt(group_a.std()**2/len(group_a) +
                 group_b.std()**2/len(group_b))
    ci_lower = diff - 1.96 * se
    ci_upper = diff + 1.96 * se
    print(f"\n📏 95% CONFIDENCE INTERVAL:")
    print(f"  Difference: {diff:.2f}")
    print(f"  CI: [{ci_lower:.2f}, {ci_upper:.2f}]")

    # Decision
    print(f"\n🎯 DECISION:")
    if p_value < alpha:
        print(f"  ✅ SIGNIFICANT (p={p_value:.4f} < {alpha})")
        if group_b.mean() > group_a.mean():
            print(f"  → Treatment B is BETTER!")
            print(f"  → RECOMMENDATION: Ship Treatment B!")
        else:
            print(f"  → Control A is BETTER!")
            print(f"  → RECOMMENDATION: Keep Control A!")
    else:
        print(f"  ❌ NOT SIGNIFICANT (p={p_value:.4f} > {alpha})")
        print(f"  → No proven difference!")
        print(f"  → RECOMMENDATION: Keep Control A!")

    print("=" * 55)
    return p_value, lift

# Test our function!
print("Testing A/B Tool on Revenue data:")
run_ab_test(group_a_revenue, group_b_revenue,
            metric_name='Zomato Revenue (₹)')

# New test — Swiggy delivery time A/B test
# Does new algorithm reduce delivery time?
np.random.seed(123)

old_algorithm = np.random.normal(loc=35, scale=8, size=500)
new_algorithm = np.random.normal(loc=33, scale=8, size=500)

print("Testing A/B Tool on Delivery Time:")
run_ab_test(old_algorithm, new_algorithm,
            metric_name='Swiggy Delivery Time (minutes)')

from google.colab import files
import os

os.makedirs('screenshots', exist_ok=True)

# Download the chart
files.download('screenshots/ab_test_results.png')
print("✅ Chart downloaded!")

!pip install reportlab -q

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import Image
import os

def generate_ab_report(group_a, group_b,
                       metric_name,
                       test_name,
                       filename='ab_test_report.pdf'):
    """Generate professional PDF report for A/B test"""

    # Run the analysis first
    t_stat, p_value = ttest_ind(group_a, group_b)
    lift = ((group_b.mean() - group_a.mean()) / group_a.mean()) * 100
    diff = group_b.mean() - group_a.mean()
    se = np.sqrt(group_a.std()**2/len(group_a) +
                 group_b.std()**2/len(group_b))
    ci_lower = diff - 1.96 * se
    ci_upper = diff + 1.96 * se
    significant = p_value < 0.05

    # Build PDF
    doc = SimpleDocTemplate(filename, pagesize=A4,
                           leftMargin=20*mm, rightMargin=20*mm,
                           topMargin=20*mm, bottomMargin=20*mm)

    styles = getSampleStyleSheet()
    story = []

    # Custom styles
    title_style = ParagraphStyle('title',
        fontSize=22, textColor=colors.HexColor('#1A1A2E'),
        fontName='Helvetica-Bold', alignment=TA_CENTER,
        spaceAfter=8)

    subtitle_style = ParagraphStyle('subtitle',
        fontSize=12, textColor=colors.HexColor('#4ECDC4'),
        fontName='Helvetica', alignment=TA_CENTER,
        spaceAfter=20)

    heading_style = ParagraphStyle('heading',
        fontSize=14, textColor=colors.HexColor('#FF6B35'),
        fontName='Helvetica-Bold', spaceBefore=14, spaceAfter=8)

    body_style = ParagraphStyle('body',
        fontSize=10, textColor=colors.HexColor('#333333'),
        fontName='Helvetica', leading=16, spaceAfter=6)

    # Title
    story.append(Paragraph("A/B Test Analysis Report", title_style))
    story.append(Paragraph(f"{test_name}", subtitle_style))
    story.append(Spacer(1, 5*mm))

    # Summary box
    if significant:
        result_color = colors.HexColor('#27AE60')
        result_text = "STATISTICALLY SIGNIFICANT"
        recommendation = f"SHIP Treatment B — {metric_name} improved!"
    else:
        result_color = colors.HexColor('#E74C3C')
        result_text = "NOT SIGNIFICANT"
        recommendation = "KEEP Control A — No proven improvement!"

    summary_data = [[
        Paragraph(f"<b>{result_text}</b>",
                 ParagraphStyle('r', fontSize=14,
                               textColor=colors.white,
                               fontName='Helvetica-Bold',
                               alignment=TA_CENTER))
    ]]
    summary_table = Table(summary_data, colWidths=[170*mm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), result_color),
        ('TOPPADDING', (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('ROUNDEDCORNERS', [8]),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 8*mm))

    # Descriptive Statistics
    story.append(Paragraph("1. Descriptive Statistics", heading_style))

    stats_data = [
        ['Metric', 'Control (A)', 'Treatment (B)', 'Difference'],
        ['Sample Size',
         str(len(group_a)),
         str(len(group_b)),
         '-'],
        [f'Mean {metric_name}',
         f'{group_a.mean():.2f}',
         f'{group_b.mean():.2f}',
         f'{diff:+.2f}'],
        ['Std Deviation',
         f'{group_a.std():.2f}',
         f'{group_b.std():.2f}',
         '-'],
        ['Min',
         f'{group_a.min():.2f}',
         f'{group_b.min():.2f}',
         '-'],
        ['Max',
         f'{group_a.max():.2f}',
         f'{group_b.max():.2f}',
         '-'],
    ]

    stats_table = Table(stats_data,
                       colWidths=[50*mm, 38*mm, 38*mm, 38*mm])
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1A1A2E')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ROWBACKGROUNDS', (0,1), (-1,-1),
         [colors.HexColor('#F8F9FA'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.3, colors.grey),
        ('TOPPADDING', (0,0), (-1,-1), 7),
        ('BOTTOMPADDING', (0,0), (-1,-1), 7),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(stats_table)
    story.append(Spacer(1, 6*mm))

    # Statistical Test Results
    story.append(Paragraph("2. Statistical Test Results", heading_style))

    test_data = [
        ['Parameter', 'Value', 'Interpretation'],
        ['T-statistic', f'{t_stat:.4f}', 'Magnitude of difference'],
        ['P-value', f'{p_value:.4f}',
         'Significant!' if significant else 'Not significant'],
        ['Significance Level (α)', '0.05', 'Standard threshold'],
        ['Lift', f'{lift:.2f}%',
         'B better' if lift > 0 else 'A better'],
        ['95% CI Lower', f'{ci_lower:.2f}', 'Minimum expected difference'],
        ['95% CI Upper', f'{ci_upper:.2f}', 'Maximum expected difference'],
    ]

    test_table = Table(test_data,
                      colWidths=[55*mm, 40*mm, 75*mm])
    test_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1A1A2E')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ROWBACKGROUNDS', (0,1), (-1,-1),
         [colors.HexColor('#F8F9FA'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.3, colors.grey),
        ('TOPPADDING', (0,0), (-1,-1), 7),
        ('BOTTOMPADDING', (0,0), (-1,-1), 7),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(test_table)
    story.append(Spacer(1, 6*mm))

    # Add chart if exists
    if os.path.exists('screenshots/ab_test_results.png'):
        story.append(Paragraph("3. Visualisation", heading_style))
        img = Image('screenshots/ab_test_results.png',
                   width=170*mm, height=80*mm)
        story.append(img)
        story.append(Spacer(1, 6*mm))

    # Recommendation
    story.append(Paragraph("4. Recommendation", heading_style))
    story.append(Paragraph(f"<b>{recommendation}</b>", body_style))
    story.append(Spacer(1, 4*mm))

    if significant:
        story.append(Paragraph(
            f"The A/B test shows a statistically significant difference "
            f"in {metric_name}. Treatment B achieves a lift of "
            f"{lift:.2f}% over Control A with p-value {p_value:.4f}. "
            f"The 95% confidence interval [{ci_lower:.2f}, {ci_upper:.2f}] "
            f"confirms Treatment B consistently outperforms Control A. "
            f"Recommend shipping Treatment B immediately.",
            body_style))
    else:
        story.append(Paragraph(
            f"The A/B test does NOT show a statistically significant "
            f"difference in {metric_name}. The observed lift of "
            f"{lift:.2f}% could be due to random chance "
            f"(p-value {p_value:.4f} > 0.05). "
            f"Recommend keeping Control A and running the test "
            f"longer with more users.",
            body_style))

    # Footer
    story.append(Spacer(1, 10*mm))
    footer_style = ParagraphStyle('footer',
        fontSize=8, textColor=colors.grey,
        fontName='Helvetica', alignment=TA_CENTER)
    story.append(Paragraph(
        "Generated by A/B Testing Tool | "
        "Prajwal Kondala | IIT Kharagpur → AI/ML Engineer",
        footer_style))

    doc.build(story)
    print(f"✅ PDF Report generated: {filename}")
    return filename

# Generate report for Zomato test!
generate_ab_report(
    group_a_revenue,
    group_b_revenue,
    metric_name='Revenue (₹)',
    test_name='Zomato Button Color Test — Blue vs Green',
    filename='ab_test_report.pdf'
)

from google.colab import files
files.download('ab_test_report.pdf')
print("✅ PDF downloaded!")

