# -*- coding: utf-8 -*-
"""ipl_cricket_analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsEuVFP5_XBtiisE_Uj2I6z9dJgya0lc
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

print("Libraries imported!")

from google.colab import files
uploaded = files.upload()

# Load the CSVs
matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')

print("MATCHES:")
print(f"Shape: {matches.shape}")
print(matches.columns.tolist())
print()
print("DELIVERIES:")
print(f"Shape: {deliveries.shape}")
print(deliveries.columns.tolist())

# Create database
os.makedirs('database', exist_ok=True)
conn = sqlite3.connect('database/ipl.db')

# Load DataFrames into SQLite
matches.to_sql('matches', conn, if_exists='replace', index=False)
deliveries.to_sql('deliveries', conn, if_exists='replace', index=False)

print("Database created!")
print(f"matches table: {pd.read_sql_query('SELECT COUNT(*) as count FROM matches', conn)['count'][0]} rows")
print(f"deliveries table: {pd.read_sql_query('SELECT COUNT(*) as count FROM deliveries', conn)['count'][0]} rows")

query = """
    SELECT winner, COUNT(*) as total_wins
    FROM matches
    WHERE winner IS NOT NULL
    GROUP BY winner
    ORDER BY total_wins DESC
    LIMIT 10
"""

df_wins = pd.read_sql_query(query, conn)
print(df_wins)

query = """
    SELECT winner, COUNT(*) as titles
    FROM matches
    WHERE match_type = 'Final'
    AND winner IS NOT NULL
    GROUP BY winner
    ORDER BY titles DESC
"""

df_titles = pd.read_sql_query(query, conn)
print(df_titles)

query = """
    SELECT batter, SUM(batsman_runs) as total_runs
    FROM deliveries
    GROUP BY batter
    ORDER BY total_runs DESC
    LIMIT 10
"""

df_batsmen = pd.read_sql_query(query, conn)
print(df_batsmen)

os.makedirs('screenshots', exist_ok=True)
print("screenshots folder created!")

plt.figure(figsize=(12, 6))
sns.barplot(data=df_batsmen, x='total_runs', y='batter',
            hue='batter', legend=False, palette='viridis')
plt.title('IPL All Time Top 10 Run Scorers (2008-2024)', fontsize=14)
plt.xlabel('Total Runs')
plt.ylabel('Batsman')
plt.tight_layout()
plt.savefig('screenshots/top_batsmen.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

plt.figure(figsize=(10, 6))
sns.barplot(data=df_titles, x='titles', y='winner',
            hue='winner', legend=False, palette='rocket')
plt.title('IPL Title Winners (2008-2024)', fontsize=14)
plt.xlabel('Number of Titles')
plt.ylabel('Team')
plt.tight_layout()
plt.savefig('screenshots/team_titles.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

query = """
    SELECT bowler, COUNT(*) as total_wickets
    FROM deliveries
    WHERE is_wicket = 1
    AND dismissal_kind NOT IN ('run out', 'retired hurt', 'obstructing the field')
    GROUP BY bowler
    ORDER BY total_wickets DESC
    LIMIT 10
"""

df_bowlers = pd.read_sql_query(query, conn)
print(df_bowlers)

plt.figure(figsize=(12, 6))
sns.barplot(data=df_bowlers, x='total_wickets', y='bowler',
            hue='bowler', legend=False, palette='magma')
plt.title('IPL All Time Top 10 Wicket Takers (2008-2024)', fontsize=14)
plt.xlabel('Total Wickets')
plt.ylabel('Bowler')
plt.tight_layout()
plt.savefig('screenshots/top_bowlers.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

query = """
    SELECT
        COUNT(*) as total_matches,
        SUM(CASE WHEN toss_winner = winner THEN 1 ELSE 0 END) as toss_winner_won,
        ROUND(SUM(CASE WHEN toss_winner = winner THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as win_percentage
    FROM matches
    WHERE winner IS NOT NULL
"""

df_toss = pd.read_sql_query(query, conn)
print(df_toss)

query = """
    SELECT m.season,
           d.batter,
           SUM(d.batsman_runs) as season_runs
    FROM matches m
    INNER JOIN deliveries d ON m.id = d.match_id
    GROUP BY m.season, d.batter
    ORDER BY m.season, season_runs DESC
    LIMIT 20
"""

df_join = pd.read_sql_query(query, conn)
print(df_join)

query = """
    WITH season_runs AS (
        SELECT m.season,
               d.batter,
               SUM(d.batsman_runs) as total_runs
        FROM deliveries d
        JOIN matches m ON d.match_id = m.id
        GROUP BY m.season, d.batter
    ),
    ranked AS (
        SELECT season, batter, total_runs,
               RANK() OVER (
                   PARTITION BY season
                   ORDER BY total_runs DESC
               ) as rnk
        FROM season_runs
    )
    SELECT season, batter, total_runs
    FROM ranked
    WHERE rnk = 1
    ORDER BY season
"""

df_top = pd.read_sql_query(query, conn)
print(df_top)

plt.figure(figsize=(14, 8))
sns.barplot(data=df_top, x='total_runs', y='season',
            hue='batter', legend=True, palette='viridis')
plt.title('IPL Season Wise Top Scorer (2008-2024)', fontsize=14)
plt.xlabel('Total Runs')
plt.ylabel('Season')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
plt.tight_layout()
plt.savefig('screenshots/season_top_scorers.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

# Toss decision analysis
query = """
    SELECT toss_decision, COUNT(*) as count
    FROM matches
    GROUP BY toss_decision
"""
df_toss_decision = pd.read_sql_query(query, conn)

plt.figure(figsize=(8, 6))
sns.barplot(data=df_toss_decision, x='toss_decision', y='count',
            hue='toss_decision', legend=False, palette='coolwarm')
plt.title('IPL Toss Decision — Bat or Field? (2008-2024)', fontsize=14)
plt.xlabel('Toss Decision')
plt.ylabel('Number of Times Chosen')
plt.tight_layout()
plt.savefig('screenshots/toss_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

# Save queries to .sql files
os.makedirs('queries', exist_ok=True)

basic_queries = """
-- Q1: Total wins per team
SELECT winner, COUNT(*) as total_wins
FROM matches
WHERE winner IS NOT NULL
GROUP BY winner
ORDER BY total_wins DESC;

-- Q2: IPL Title Winners (Finals only)
SELECT winner, COUNT(*) as titles
FROM matches
WHERE match_type = 'Final'
AND winner IS NOT NULL
GROUP BY winner
ORDER BY titles DESC;

-- Q3: Top 10 batsmen all time
SELECT batter, SUM(batsman_runs) as total_runs
FROM deliveries
GROUP BY batter
ORDER BY total_runs DESC
LIMIT 10;

-- Q4: Top 10 wicket takers
SELECT bowler, COUNT(*) as total_wickets
FROM deliveries
WHERE is_wicket = 1
AND dismissal_kind NOT IN ('run out', 'retired hurt', 'obstructing the field')
GROUP BY bowler
ORDER BY total_wickets DESC
LIMIT 10;

-- Q5: Toss analysis
SELECT
    COUNT(*) as total_matches,
    SUM(CASE WHEN toss_winner = winner THEN 1 ELSE 0 END) as toss_winner_won,
    ROUND(SUM(CASE WHEN toss_winner = winner THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as win_percentage
FROM matches
WHERE winner IS NOT NULL;
"""

with open('queries/01_basic_queries.sql', 'w') as f:
    f.write(basic_queries)

print("SQL files saved!")

conn.close()
print("Database connection closed!")