# -*- coding: utf-8 -*-
"""stock_market_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NioRoX4soxJzRxmIWgKXxpdiJeGYI0j
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported!")

# Fetch Reliance Industries data — 1 year!
reliance = yf.download('RELIANCE.NS',
                        start='2024-01-01',
                        end='2025-01-01',
                        progress=False)

print("Reliance Industries Data:")
print(f"Shape: {reliance.shape}")
print(f"\nColumns: {reliance.columns.tolist()}")
print(f"\nFirst 5 rows:")
print(reliance.head())

# Flatten column names
reliance.columns = ['Close', 'High', 'Low', 'Open', 'Volume']

# Reset index so Date becomes a column
reliance = reliance.reset_index()

print("Cleaned DataFrame:")
print(reliance.head())
print(f"\nShape: {reliance.shape}")
print(f"\nColumns: {reliance.columns.tolist()}")

# Calculate 20-day and 50-day moving averages
reliance['MA20'] = reliance['Close'].rolling(window=20).mean()
reliance['MA50'] = reliance['Close'].rolling(window=50).mean()

print("With Moving Averages:")
print(reliance.head(25))

# Create candlestick chart
fig = go.Figure(data=[go.Candlestick(
    x=reliance['Date'],
    open=reliance['Open'],
    high=reliance['High'],
    low=reliance['Low'],
    close=reliance['Close'],
    name='Reliance'
)])

fig.update_layout(
    title='Reliance Industries — Candlestick Chart 2024',
    xaxis_title='Date',
    yaxis_title='Price (₹)',
    template='plotly_dark',
    height=600
)

fig.show()

# Add MA20 and MA50 lines to candlestick
fig.add_trace(go.Scatter(
    x=reliance['Date'],
    y=reliance['MA20'],
    name='MA20',
    line=dict(color='orange', width=1.5)
))

fig.add_trace(go.Scatter(
    x=reliance['Date'],
    y=reliance['MA50'],
    name='MA50',
    line=dict(color='blue', width=1.5)
))

fig.update_layout(
    title='Reliance Industries — Candlestick + Moving Averages 2024',
)

fig.show()

import os
os.makedirs('screenshots', exist_ok=True)

# Save as interactive HTML
fig.write_html('screenshots/reliance_candlestick.html')
print("✅ Candlestick saved as HTML!")

# Define Indian stocks to analyze
tickers = {
    'Reliance': 'RELIANCE.NS',
    'TCS': 'TCS.NS',
    'Infosys': 'INFY.NS',
    'HDFC Bank': 'HDFCBANK.NS',
    'Wipro': 'WIPRO.NS'
}

# Fetch all stocks
all_data = {}
for name, ticker in tickers.items():
    data = yf.download(ticker,
                       start='2024-01-01',
                       end='2025-01-01',
                       progress=False)
    data.columns = ['Close', 'High', 'Low', 'Open', 'Volume']
    data = data.reset_index()
    all_data[name] = data
    print(f"✅ {name}: {data.shape[0]} trading days")

print("\nAll stocks fetched!")

fig2 = go.Figure()

for name, data in all_data.items():
    # Normalize to 100 for fair comparison
    normalized = (data['Close'] / data['Close'].iloc[0]) * 100

    fig2.add_trace(go.Scatter(
        x=data['Date'],
        y=normalized,
        name=name,
        mode='lines'
    ))

fig2.update_layout(
    title='Indian Stocks — Normalized Performance 2024 (Base=100)',
    xaxis_title='Date',
    yaxis_title='Normalized Price (Base=100)',
    template='plotly_dark',
    height=600
)

fig2.show()
fig2.write_html('screenshots/multi_stock_comparison.html')
print("✅ Multi-stock comparison saved!")

# Calculate daily returns for each stock
returns_data = {}

for name, data in all_data.items():
    returns_data[name] = data['Close'].pct_change() * 100  # percentage

returns_df = pd.DataFrame(returns_data)
returns_df.index = all_data['Reliance']['Date']

print("Daily Returns (%):")
print(returns_df.describe().round(2))

# Calculate correlation between stocks
correlation = returns_df.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation,
            annot=True,
            fmt='.2f',
            cmap='RdYlGn',
            center=0,
            square=True,
            linewidths=0.5)

plt.title('Indian Stocks — Return Correlation Heatmap 2024', fontsize=14, pad=20)
plt.tight_layout()
plt.savefig('screenshots/correlation_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Correlation heatmap saved!")

fig3 = go.Figure()

for name in returns_df.columns:
    volatility = returns_df[name].rolling(window=30).std()
    fig3.add_trace(go.Scatter(
        x=returns_df.index,
        y=volatility,
        name=name,
        mode='lines'
    ))

fig3.update_layout(
    title='Indian Stocks — 30-Day Rolling Volatility 2024',
    xaxis_title='Date',
    yaxis_title='Volatility (%)',
    template='plotly_dark',
    height=600
)

fig3.show()
fig3.write_html('screenshots/volatility_comparison.html')
print("✅ Volatility chart saved!")

# Calculate annual return for each stock
annual_returns = {}

for name, data in all_data.items():
    start_price = data['Close'].iloc[0]
    end_price = data['Close'].iloc[-1]
    annual_return = ((end_price - start_price) / start_price) * 100
    annual_returns[name] = round(annual_return, 2)

returns_summary = pd.DataFrame({
    'Stock': list(annual_returns.keys()),
    'Annual Return (%)': list(annual_returns.values())
}).sort_values('Annual Return (%)', ascending=False)

print("Annual Returns 2024:")
print(returns_summary)

# Visualize
plt.figure(figsize=(10, 6))
colors = ['green' if x > 0 else 'red' for x in returns_summary['Annual Return (%)']]
sns.barplot(data=returns_summary,
            x='Annual Return (%)',
            y='Stock',
            hue='Stock',
            legend=False,
            palette=colors)
plt.title('Indian Stocks — Annual Return 2024 (%)', fontsize=14)
plt.xlabel('Annual Return (%)')
plt.axvline(x=0, color='white', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('screenshots/returns_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Returns chart saved!")

# Print key insights
print("=" * 50)
print("KEY INSIGHTS — Indian Stocks 2024")
print("=" * 50)

# Best performer
best = returns_summary.iloc[0]
worst = returns_summary.iloc[-1]
print(f"\n🏆 Best Performer: {best['Stock']} ({best['Annual Return (%)']:.1f}%)")
print(f"📉 Worst Performer: {worst['Stock']} ({worst['Annual Return (%)']:.1f}%)")

# Most volatile
avg_vol = returns_df.std()
most_volatile = avg_vol.idxmax()
least_volatile = avg_vol.idxmin()
print(f"\n⚡ Most Volatile: {most_volatile} (std: {avg_vol[most_volatile]:.2f}%)")
print(f"🛡️ Most Stable: {least_volatile} (std: {avg_vol[least_volatile]:.2f}%)")

# Highest correlation pair
corr = returns_df.corr()
# Remove self-correlations
corr_unstacked = corr.unstack()
corr_unstacked = corr_unstacked[corr_unstacked < 1.0]
most_correlated = corr_unstacked.idxmax()
print(f"\n🔗 Most Correlated Pair: {most_correlated[0]} & {most_correlated[1]}")
print(f"   Correlation: {corr_unstacked.max():.2f}")
print("=" * 50)

from google.colab import files

for file in os.listdir('screenshots'):
    files.download(f'screenshots/{file}')
    print(f"⬇️ Downloaded: {file}")

print("✅ All files downloaded!")